### ISSUE TITLE
carousel 코드 관련 질문 입니다.

### ISSUE THREAD

**Issue by fireworks80** [yamoo9/Modern.JS#1]
안녕하세요.
carousel.js 코드를 보다가 궁금한것이 있어서요....
제가 js를 잘 못해서 일 수 있는데.......
carousel 생성자 함수를 만들고 jquery shall이라는 곳에서 new 로 생성자 함수로 넣으셨는데...
$.fn.carousel 안에서 만들지 않고 따로 carousel 생성자 함수를 만드신 이유가 있으신지요.....

**Comment by yamoo9** [comment]
jQuery 플러그인 제작 방식은 크게 다음 2가지가 있습니다.

- 함수형 플러그인
- 클래스형 플러그인

제가 사용한 방식은 클래스형 플러그인으로 JavaScript Prototype 객체를 사용합니다.
이 방식은 함수형 플러그인의 문제점을 해결할 수 있습니다.

함수형 플러그인의 문제점은 플러그인을 사용할 때마다 플러그인 내부에 
사용 되는 함수가 재사용 되지 않고, 중복 생성되는 문제를 가지고 있습니다.

이 문제를 피해갈 수 있는 방법이 클래스형 플러그인 입니다.
