### ISSUE TITLE
안녕하세요 모던 자바스크립트 교육 받았던 교육생입니다.

### ISSUE THREAD

**Issue by super8ky** [yamoo9/Modern.JS#3]
vue.js 관련 슬라이드 올려주신다고 하셨는데 언제쯤 올려주시나요?^^;;  파일 부탁드립니다~ ^^;

**Comment by yamoo9** [comment]
@super8ky 님

요청주신 PDF 올렸습니다. 아래 링크를 클릭하면 확인하실 수 있어요~ ^^ 

[Vue.js PDF](https://github.com/yamoo9/Modern.JS/tree/2017.10/WEEK__03/Vue.js%20PDF)
